???services:
  - type: web
    name: dacp
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 18
    routes:
      - type: rewrite
        source: /api/*
        destination: https://dacp-backend.onrender.com/api/*
      - type: rewrite
        source: /.+
        destination: /index.html
